const products = [
  {
    id: 1,
    title: "Cajitas",
    price: 1000,
    image: "img/img1.jpg",
    stock: 13,
  },
  {
    id: 2,
    title: "Cojines",
    price: 2000,
    image: "img/img2.jpg",
    stock: 12,
  },
  {
    id: 3,
    title: "Copas",
    price: 3000,
    image: "img/img3.jpg",
    stock: 11,
  },
  {
    id: 4,
    title: "Toppers",
    price: 4000,
    image: "img/img4.jpg",
    stock: 10,
  },
  {
    id: 5,
    title: "Mini Toppers",
    price: 5000,
    image: "img/img5.jpg",
    stock: 9,
  },
  {
    id: 6,
    title: "Vinilo Decorativos",
    price: 6000,
    image: "img/img6.jpg",
    stock: 8,
  },
  {
    id: 7,
    title: "Cajitas",
    price: 7000,
    image: "img/img7.jpg",
    stock: 7,
  },
  {
    id: 8,
    title: "Cajitas",
    price: 8000,
    image: "img/img8.jpg",
    stock: 6,
  },
  {
    id: 9,
    title: "Toppers",
    price: 9000,
    image: "img/img9.jpg",
    stock: 5,
  },
  {
    id: 10,
    title: "Toppers",
    price: 10000,
    image: "img/img10.jpg",
    stock: 4,
  },
  {
    id: 11,
    title: "Cajitas",
    price: 11000,
    image: "img/img11.jpg",
    stock: 3,
  },
  {
    id: 12,
    title: "Toppers",
    price: 12000,
    image: "img/img12.jpg",
    stock: 2,
  },
];

export default products;