const products = [
  {
    id: 1,
    title: "Cajitas Decoradas de Cumpleaños",
    price: "1.000",
    image: "img/img1.jpg",
    stock: 13,
  },
  {
    id: 2,
    title: "Cojines de Tela Personalizados, sin estampado",
    price: "2.000",
    image: "img/img2.jpg",
    stock: 12,
  },
  {
    id: 3,
    title: "Copas de Vino Decoradas con Nombres",
    price: "3.000",
    image: "img/img3.jpg",
    stock: 11,
  },
  {
    id: 4,
    title: "Toppers Temáticos personalizados",
    price: "4.000",
    image: "img/img4.jpg",
    stock: 10,
  },
  {
    id: 5,
    title: "Mini Toppers Temáticos personalizados",
    price: "5.000",
    image: "img/img5.jpg",
    stock: 9,
  },
  {
    id: 6,
    title: "Vinilo Decorativos - Superficies Interiores",
    price: "6.000",
    image: "img/img6.jpg",
    stock: 8,
  },
  {
    id: 7,
    title: "Cajitas Variadas Personalizada para Eventos",
    price: "7.000",
    image: "img/img7.jpg",
    stock: 7,
  },
  {
    id: 8,
    title: "Cajitas Decoradas de Cumpleaños",
    price: "8.000",
    image: "img/img8.jpg",
    stock: 6,
  },
  {
    id: 9,
    title: "Toppers Temáticos personalizados",
    price: "9.000",
    image: "img/img9.jpg",
    stock: 5,
  },
  {
    id: 10,
    title: "Toppers Temáticos personalizados",
    price: "10.000",
    image: "img/img10.jpg",
    stock: 4,
  },
  {
    id: 11,
    title: "Cajitas Decoradas de Cumpleaños",
    price: "11.000",
    image: "img/img11.jpg",
    stock: 3,
  },
  {
    id: 12,
    title: "Toppers Temáticos personalizados",
    price: "12.000",
    image: "img/img12.jpg",
    stock: 2,
  },
];

export default products;